name: Update Secure Code

on:
  schedule:
    - cron: '*/5 * * * *' # co 5 minut

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate new 4-digit code
        run: |
          CODE=$(shuf -i 1000-9999 -n 1)
          echo "{\"code\": \"$CODE\"}" > secure-code.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add secure-code.json
          git commit -m "Update secure code to $CODE" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mariuszsyrek/mariuszsyrek.git