name: Update Secure Code

on:
  schedule:
    - cron: '*/2 * * * *' # co 2 minuty

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate new 4-digit code
        run: |
          CODE=$(shuf -i 1000-9999 -n 1)
          echo "{\"code\": \"$CODE\"}" > secure-code.json

          # Wymuszamy zmianę dummy pliku, by commit był zawsze inny
          echo "// timestamp: $(date)" > dummy.txt

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add secure-code.json dummy.txt
          git commit -m "Update secure code to $CODE at $(date)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mariuszsyrek/mariuszsyrek.git
